---
title: "ForC Database"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Database overview
The Forest C database (ForC-db) is an open access global C database led by Dr. Kristina Anderson-Teixeira (Smithsonian). ForC is updated and maintained in [this Github repository](https://github.com/forc-db/ForC) and is [visualized here](https://forc.shinyapps.io/global_data_visualization/). The database contains previously published data on ground-based measurements of ecosystem-level C stocks and annual fluxes in forests globally, along with site information, disturbance history, and information on methodology. It currently contains >17,500 records from >2,700 plots and >2,000 sites, making it the largest and most comprehensive database of its type. These data were obtained from multiple previous compilations and individual published studies, as detailed in [Anderson-Teixeira et al. (2016)](http://onlinelibrary.wiley.com/doi/10.1111/gcb.13226/abstract) and [Anderson-Teixeira et al. (2018)](https://esajournals.onlinelibrary.wiley.com/doi/10.1002/ecy.2229).


![**Geographical distributions of sites included in ForC-db.** Symbols are colored according to the number of records from each site. Underlying map shows coverage of evergreen, deciduous, and mixed forests (from SYNMAP; Jung et al. 2006) and biogeographic zones (Olson et al. 2001). Distribution of sites, plots, and records among biogeographic zones is shown in the inset.](https://github.com/forc-db/ForC/blob/master/figures/World_Map_with_Biogeographic_regions_and_sites.png?raw=true)



Previous versions of ForC have been published in the peer-reviewed literature: [Anderson-Teixeira et al. (2016)](http://onlinelibrary.wiley.com/doi/10.1111/gcb.13226/abstract) and [Anderson-Teixeira et al. (2018)](https://esajournals.onlinelibrary.wiley.com/doi/10.1002/ecy.2229). ForC is continuously developing, and the version on Github is always the current master. Interested users may contact database PI Dr. Kristina Anderson-Teixeira for an update on status and to discuss collaboration. 

## Data Use 
ForC-db is an open access database, and we encourage use of the data for scientific research and educational purposes. All users are responsible to adhere to the data use policy: [`DATA USE.md`](https://github.com/forc-db/ForC/blob/master/DATA%20USE.md). 


## Contributing to the database 
We anticipate that ForC-db will be of great value for various initiatives seeking to understand and manage the role of tropical forests in the global C cycle, and we encourage authors to contribute data. Please see [`CONTRIBUTING.md`](https://github.com/forc-db/ForC/blob/master/CONTRIBUTING.md).


## Database citations
Any publications using ForC data should cite the following publications: 

* Anderson-Teixeira, K.J. *et al.* 2016. Carbon dynamics of mature and regrowth tropical forests derived from a pantropical database (TropForC-db). Global Change Biology. DOI: [10.1111/gcb.13226](http://dx.doi.org/10.1111/gcb.13226) 

* Anderson-Teixeira, K. J., M. M. H. Wang, J. C. McGarvey, V. Herrmann, A. J. Tepley, B. P. Bond-Lamberty, and D. S. LeBauer. in press. ForC: a global database of forest carbon stocks and fluxes. Ecology. DOI: [10.1002/ecy.2229](https://esajournals.onlinelibrary.wiley.com/doi/10.1002/ecy.2229).

In addition, if data are obtained from [the Github repository](https://github.com/forc-db/ForC) (as opposed to a static version associated with one of the above publications), this should be referenced as well (DOI representing all versions: [10.5281/zenodo.1135088](https://doi.org/10.5281/zenodo.1187192)). Publications should cite a specific version of ForC, ideally with a DOI associated with that version. Authors may work with ForC managers to generate a release and associated DOI that matches the database version used in their publication.


## Funding acknowledgements
* DOE Terrestrial Ecosystem Science grant DE-SC0008085/ DE-SC0010039 to Kristina Anderson-Teixeira, Evan DeLucia, and Benjamin Duval

* Smithsonian Women's Committee grant to Kristina Anderson-Teixeira

* Smithsonian Scholarly Studies grant to Kristina Anderson-Teixeira and Helene Muller-Landau
