---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<br>

# Publications
<br>

### Database publications

* Anderson-Teixeira, K. J., M. M. H. Wang, J. C. McGarvey, V. Herrmann, A. J. Tepley, B. P. Bond-Lamberty, and D. S. LeBauer (2018) [ForC: a global database of forest carbon stocks and fluxes](https://esajournals.onlinelibrary.wiley.com/doi/10.1002/ecy.2229). Ecology. DOI: 10.1002/ecy.2229.

* Anderson-Teixeira, K.J., Wang, M. M. H., McGarvey, J.C., and LeBauer, D.S. (2016) [Carbon dynamics of mature and regrowth tropical forests derived from a pantropical database (TropForC-db)](http://dx.doi.org/10.1111/gcb.13226). Global Change Biology. DOI: 10.1111/gcb.13226.

<br>

### Publications using ForC data
(incomplete list)

* Rozendaal, D. M. A., D. R. Suarez, V. D. Sy, V. Avitabile, S. Carter, C. Y. A. Yao, E. Alvarez-Davila, K. Anderson-Teixeira, A. Araujo-Murakami, L. Arroyo, B. Barca, T. R. Baker, L. Birigazzi, F. Bongers, A. Branthomme, R. J. W. Brienen, J. M. B. Carreiras, R. C. Gatti, S. C. Cook-Patton, M. Decuyper, B. DeVries, A. B. Espejo, T. R. Feldpausch, J. Fox, J. G. P. Gamarra, B. W. Griscom, N. Harris, B. Hérault, E. N. H. Coronado, I. Jonckheere, E. Konan, S. M. Leavitt, S. L. Lewis, J. A. Lindsell, J. K. N’Dja, A. E. N’Guessan, B. Marimon, E. T. A. Mitchard, A. Monteagudo, A. Morel, A. Pekkarinen, O. L. Phillips, L. Poorter, L. Qie, E. Rutishauser, C. M. Ryan, M. Santoro, D. S. Silayo, P. Sist, J. W. F. Slik, B. Sonké, M. J. P. Sullivan, G. V. Laurin, E. Vilanova, M. M. H. Wang, E. Zahabu, and M. Herold. 2022. [Aboveground forest biomass varies across continents, ecological zones and successional stages: refined IPCC default values for tropical and subtropical forests](https://doi.org/10.1088/1748-9326/ac45b3). Environmental Research Letters 17:014047. 

* Anderson‐Teixeira, K., Herrmann, V., Banbury Morgan, R., Bond‐Lamberty, B. P., Cook‐Patton, S. C., Ferson, A. E., Muller‐Landau, H. C., & Wang, M. M. H.(2021). [Carbon cycling in mature and regrowth forests globally](https://doi.org/10.1088/1748-9326/abed01). Environmental Research Letters, 16 053009. 

* Banbury Morgan R, Herrmann V, Kunert N, Bond-Lamberty B, Muller-Landau H C and Anderson-Teixeira K J. (2021) [Global patterns of forest autotrophic carbon fluxes](https://doi.org/10.1111/gcb.15574). Global Change Biology,  27 (12) 2840-2855.  

* Cook-Patton S C, Leavitt S M, Gibbs D, Harris N L, Lister K, Anderson-Teixeira K J, Briggs R D, Chazdon R L, Crowther T W, Ellis P W, Griscom H P, Herrmann V, Holl K D, Houghton R A, Larrosa C, Lomax G, Lucas R, Madsen P, Malhi Y, Paquette A, Parker J D, Paul K, Routh D, Roxburgh S, Saatchi S, Hoogen J van den, Walker W S, Wheeler C E, Wood S A, Xu L and Griscom B W 2020 [Mapping carbon accumulation potential from global natural forest regrowth](http://www.nature.com/articles/s41586-020-2686-x). Nature 585 545–50

* Goldstein, A., Turner, W. R., Spawn, S. A., Anderson-Teixeira, K. J., Cook-Patton, S., Fargione, J., Gibbs, H. K., Griscom, B., Hewson, J. H., Howard, J. F., Ledezma, J. C., Page, S., Koh, L. P., Rockström, J., Sanderman, J., & Hole, D. G. (2020). [Protecting irrecoverable carbon in Earth’s ecosystems](https://doi.org/10.1038/s41558-020-0738-8). Nature Climate Change, 1–9. 

* Requena Suarez, D., D. M. A. Rozendaal, V. D. Sy, O. L. Phillips, E. Alvarez‐Dávila, K. Anderson‐Teixeira, A. Araujo‐Murakami, L. Arroyo, T. R. Baker, F. Bongers, R. J. W. Brienen, S. Carter, S. C. Cook‐Patton, T. R. Feldpausch, B. W. Griscom, N. Harris, B. Hérault, E. N. H. Coronado, S. M. Leavitt, S. L. Lewis, B. S. Marimon, A. M. Mendoza, J. K. N’dja, A. E. N’Guessan, L. Poorter, L. Qie, E. Rutishauser, P. Sist, B. Sonké, M. J. P. Sullivan, E. Vilanova, M. M. H. Wang, C. Martius, and M. Herold. (2019). [Estimating aboveground net biomass change for tropical and subtropical forests: refinement of IPCC default rates using forest plot data](https://onlinelibrary.wiley.com/doi/abs/10.1111/gcb.14767). Global Change Biology, 25(11), 3609-3624. DOI: 10.1111/nph.15906